### ISSUE TITLE
5.0.0. DemoStorage Exception

### ISSUE THREAD

**Issue by papachoco** [zopefoundation/ZODB#103]
Hi,

In line 330 of DemoStorage.py (see below) we are not returning after we calling self.changes.storeBlob so the previous attribute error is always raised.

Thanks a lot,

Carlos

           if self._blobify():
                self.changes.storeBlob(
                    oid, oldserial, data, blobfilename, '', transaction)
            raise

**Comment by jamadden** [comment]
Which is now line [383 in master](https://github.com/zopefoundation/ZODB/blob/master/src/ZODB/DemoStorage.py#L383).

The return statement was dropped in https://github.com/zopefoundation/ZODB/commit/7e1db13fa462467434c2693a0cee34bc5069a74c ("Switch all storages to the new commit protocol").

I suspect a simple `return` would take care of it, but presumably this code isn't covered by test cases 😞

**Comment by jmuchemb** [comment]
You're right. I removed the `return`s so that the method always returns None, but I forgot to add a return after the second call to `storeBlob` (or maybe a `else: raise` is better).

**Comment by jamadden** [comment]
I'm working on a PR with test.
