### ISSUE TITLE
Writing persistent objects

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/ZODB#113]
_From @jimfulton on August 26, 2016 13:10_

Plus:

- Added machinery to text documentation examples

- Cleaned up config a bit

_Copied from original issue: zopefoundation/zodbdocs/pull/22_

**Comment by tseaver** [comment]
_From @jamadden on August 26, 2016 16:13_

The text looks pretty good to me, other than the occasional minor typo or possibility to add a link. I didn't look at the build, but it passed, and I like the idea of tests!

Here's why I think linking to zope.cachedesciptors, etc, might be a good idea: One of the good things about ZODB is that there are packages that can handle many different problems you might run into (e.g., `zope.cachedescriptors` handles `_v_` attributes for you) but there's never been a central place telling you what's out there, what it's good for, and when you might want to use it. This document might be a good place to pull some of those things together.

**Comment by tseaver** [comment]
_From @jimfulton on August 27, 2016 16:21_

I like the idea of including some links. I'll add some at the end of the topic. Please feel free to suggest/add more.

Update: added

**Comment by tseaver** [comment]
_From @mauritsvanrees on August 29, 2016 9:38_

Clear and concise.

I have fixed a few minor typos on the branch.

**Comment by jamadden** [comment]
The original issue zopefoundation/zodbdocs#12  was closed so this should be too.
