### ISSUE TITLE
Weird discarded comparison lurking in untested code

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/ZODB#13]
I was reading the source code for some reason yesterday and I noticed this bit in [FileStorage.py](https://github.com/zopefoundation/ZODB/blob/70a03207bc1095066a7b228bc19386e7fa72b51b/src/ZODB/FileStorage/FileStorage.py#L1639-1647), in the `read_index` function:
```python
    # Caution:  fsIndex doesn't have an efficient __nonzero__ or __len__.
    # That's why we do try/except instead.  fsIndex.maxKey() is fast.
    try:
        maxoid = index.maxKey()
    except ValueError:
        # The index is empty.
        maxoid == z64

    return pos, maxoid, ltid
```

I think the `except` branch meant to do an assignment instead of a comparison.  There are no other assignments to `maxoid` in this function, so this branch, if ever taken, would raise an UnboundLocalError.

I don't have the time right now to come up with a unit test triggering this, or I'd fix it.  But I don't want it to be forgotten, so I'm filing this isssue.

**Comment by tseaver** [comment]
- It won't be an UnboundLocalError, because `maxoid` is a (long-unused, BBB) parameter to `read_index`.

- Even better, I don't think that `index.maxKey()` without args can raise a ValueError:  that only happens when an explicit comparison key is passed, but no key is greater.

**Comment by kilink** [comment]
Calling maxKey() on an empty BTree will throw a ValueError:

```python
>>> x = BTrees.OOBTree.OOBTree()
>>> x.maxKey()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: empty tree
```

**Comment by tseaver** [comment]
Ah, OK.  I don't think it is ever possible to have load an empty `fsTree` from a file, though:  it is always at least going to have the root object in it, or it wouldn't have been created at all.

**Comment by jmuchemb** [comment]
The index is empty when a FileStorage DB is being created. It's also possible to create one without adding a root object. The following code actually causes a ValueError twice:
```python
FileStorage("foo").close()
FileStorage("foo")
```
So the `except` clause is important and there's no need to add a unit test. 96183018d9b9014f594f04e215c679b942176038 clarifies the code.
