### ISSUE TITLE
BaseStorage.copyTransactionsFrom fails to copy extension data.

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/ZODB#130]
From [this comment](https://github.com/zopefoundation/ZODB/pull/129#discussion_r88463541). 

Should it? If so, RelStorage should too.

**Comment by jamadden** [comment]
Nope, I'm wrong. The data goes by many names.

**Comment by jimfulton** [comment]
What makes you think it doesn't?

**Comment by jimfulton** [comment]
nm :)
