### ISSUE TITLE
ZODB4 incompatibility with transaction 2.0.3 on python2

### ISSUE THREAD

**Issue by sblondon** [zopefoundation/ZODB#133]
The error occurs on python2 only (works with python3).

With transaction v.2.0.3, the database description fields must now be set with unicode. The code provides the byte string, not unicode:
ZODB.DB.py, line 455: t.description = 'initial database creation'

How to reproduce
----------------------
```
$ virtualenv -p python2 venv
$ ./venv/bin/pip install zodb==4.4.3
$ ./venv/bin/python
Python 2.7.3 (default, Jun 22 2015, 19:33:41) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ZODB
>>> ZODB.DB(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stephane/src/demo_bug_yzodb/venv/local/lib/python2.7/site-packages/ZODB/DB.py", line 455, in __init__
    t.description = 'initial database creation'
  File "/home/stephane/src/demo_bug_yzodb/venv/local/lib/python2.7/site-packages/transaction/_transaction.py", line 149, in description
    raise TypeError("Description must be text (unicode)")
TypeError: Description must be text (unicode)
```

How to fix
----------

ZODB.DB.py, line 455: 
```
--- DB.orig.py	2016-11-25 15:26:06.303698887 +0100
+++ DB.py	2016-11-25 15:26:20.603572351 +0100
@@ -452,7 +452,7 @@
                 p.dump((root.__class__, None))
                 p.dump(root.__getstate__())
                 t = transaction.Transaction()
-                t.description = 'initial database creation'
+                t.description = u'initial database creation'
                 temp_storage.tpc_begin(t)
                 temp_storage.store(z64, None, file.getvalue(), '', t)
                 temp_storage.tpc_vote(t)
```

I can do a pull/request if you want.
I didn't check if the fix is relevant for other branches of ZODB.

**Comment by jimfulton** [comment]
Oops, I forgot to update ZODB 4. I'm working on that now.

The change above is one of many needed (because tests).

**Comment by sblondon** [comment]
Thank you Jim for the quick fix.

Do you know if there will be a new release (v. 4.4.4?) of zodb4 to provide the fix to pypi.python.org?

Our current workaround is to add an artificial dependency to 'transaction<=2.0.2' so it's not a big problem for us but it would be better to increase the dependency to a fixed zodb library.

**Comment by jimfulton** [comment]
I just released 4.4.4.

**Comment by jmuchemb** [comment]
> I just released 4.4.4.

@jimfulton Can you please push the release commit (along with a tag)?

**Comment by jimfulton** [comment]
Done. Sorry.

**Comment by sblondon** [comment]
Thank you Jim for all your work!
