### ISSUE TITLE
Why are the permissions for blobs hardcoded to give only the user access?

### ISSUE THREAD

**Issue by enfold-josh** [zopefoundation/ZODB#155]
Currently the blobs code creates directories with permissions giving only user read, write and execute and files with permissions giving only user read. This is hardcoded and impossible to change without patching.

We have a client that wants to use solr to index content. To index blobs using collective.solr solr requires permissions to access the blobs on the filesystem. Currently without patching this would require the solr process to run as the same user as the zope processes. This is problematic because the solr process would then have write access to the blobstorage directories.

**Comment by jimfulton** [comment]
This is a horrible misfeature.

**Comment by jimfulton** [comment]
Note: https://github.com/zopefoundation/ZODB/pull/1
