### ISSUE TITLE
TypeError with OOTree.__getitem__ for composed keys containing None with py3

### ISSUE THREAD

**Issue by ml31415** [zopefoundation/ZODB#167]
```
from BTrees.OOBTree import OOBTree
keys = [('a', 100), ('b', 200), ('c', None)]

tree = OOBTree()
for i, key in enumerate(keys):
    tree[key] = i

tree[('c', None)] # works
tree[('a', None)] # TypeError
tree[(None, None)] # TypeError

```
I recently migrated from py2, where the above code worked fine. With py3, the more strict comparison seems to cause some trouble. Tested with the latest version from pypi.

**Comment by jamadden** [comment]
This would not seem to be ZODB specific and as such would be better reported to the zopefoundation/BTrees repo. 

Thanks for your report!

**Comment by ml31415** [comment]
Will do, thanks.
