### ISSUE TITLE
README should make it clearer which Python versions aret supported

### ISSUE THREAD

**Issue by paul-hammant** [zopefoundation/ZODB#168]
Same's true for Sphinx site.

Also pls do some Canonical-URL work so that Google's search index can purge itself of "old" documentation - https://publicobject.com/2017/02/14/canonical-urls-for-javadocs/

**Comment by jamadden** [comment]
Python 3 is fully supported and has been for some time. 

A google search for “ZODB” returns correct, current results AFAICS.

**Comment by paul-hammant** [comment]
Well there's commentary elsewhere on the internet that Python 3 is not supported.  

Perhaps then: "README should make it clearer that Python 3 is supported"

**Comment by mgedmin** [comment]
A good way of checking Python 3 support status is to look at the bottom of the PyPI page:

![ekrano nuotrauka is 2017-07-24 14-30-29](https://user-images.githubusercontent.com/159967/28521508-b0c1dfbe-707c-11e7-96ac-70be65320194.png)

(or you can look at the same information in [setup.py](https://github.com/zopefoundation/ZODB/blob/master/setup.py) in Git).

It is perhaps not the most discoverable location, especially given the size of our PyPI page.  A brief additional mention in the README would not hurt.

ZODB is a bit of a special case in that we support both Python 2 and Python 3, but the database formats are incompatible between 2 and 3 (so you cannot use a database created on Python 2 with an application running on Python 3 or vice versa.)  I don't know where this is documented -- couldn't find it on www.zodb.org anywhere.  Looks like a gap in our docs!

**Comment by jamadden** [comment]
(I'm working on a PR for Python 3.6 support and will add a note about supported versions to the readme and docs.)

**Comment by tseaver** [comment]
Could we add a badge to `README.rst`?  E.g.:

```rst
.. image:: https://img.shields.io/pypi/pyversions/ZODB.svg
   :target: https://pypi.org/project/ZODB/
```

**Comment by paul-hammant** [comment]
Good job, team, thanks.

**Comment by mgedmin** [comment]
I like the badge idea!

I'm not sure if we want to rely on shields.io -- in the past their badges were often unreliable, displaying broken images.

**Comment by tseaver** [comment]
@mgedmin I added badges this morning.  Is there an alternative to shields.io?

**Comment by tomgross** [comment]
https://badge.fury.io/for/py/ZODB

**Comment by icemac** [comment]
@tomgross Is there a way to tell BadgeFury to render the supported Python versions instead of the current version released on PyPI?

**Comment by mgedmin** [comment]
Let's wait and see if the shields.io people solved their reliability problems.
