### ISSUE TITLE
how to check the existence of an object in root

### ISSUE THREAD

**Issue by yyz1989** [zopefoundation/ZODB#175]
Hey there,

Before I want to put something under "root", I will check if the object exists first, so I came up with
```
root = conn.root
        if "users" not in root:
            root.users = BTrees.OOBTree.BTree()
```
But I got a
```
TypeError: argument of type 'RootConvenience' is not iterable
```
Then I also tried
```
if not root.users
if not root["users"]
if not root.has_key("users")
```
Unfortunately none of them work. Should I catch that exception and then create a new object?

Many thanks for any suggestion.

Best regards,
Yang

**Comment by jamadden** [comment]
You want `conn.root()`:

```pycon
>>> import ZODB, ZODB.DemoStorage
>>> db = ZODB.DB(ZODB.DemoStorage.DemoStorage())
>>> conn = db.open()
>>> 'foo' in conn.root()
False
>>> conn.root()['foo'] = 'bar'
>>> 'foo' in conn.root()
True
```

As the name `RootConvenience` implies, `conn.root` is just a (partial) shortcut for `conn.root()`.

**Comment by jamadden** [comment]
Oh, and I guess you can also use `hasattr`:
```pycon
>>> hasattr(conn.root, 'foo')
True
>>> hasattr(conn.root, 'baz')
False
```

I'm not sure why `RootConvenience` doesn't also support `__contains__` (or indeed more of the mapping API), but it doesn't. It's attribute based. For the mapping interface, you need to call it.

**Comment by jamadden** [comment]
I think this is pretty well answered so I'm going to go ahead and close this. If you have issues feel free to reopen.

**Comment by yyz1989** [comment]
@jamadden Thanks a lot for the answer! I see, my fault.

**Comment by jimfulton** [comment]
Thanks for the thanks. It's appreciated!

But you're not at fault for something that could probably be clearer. There is a weird dichotomy between mapping and object behavior here.  (It has historical roots, but that's a reason, not and an excuse.)

**Comment by jimfulton** [comment]
See #176
