### ISSUE TITLE
[Q] How does ZODB serialize/deserialize pandas DataFrames?

### ISSUE THREAD

**Issue by rs2** [zopefoundation/ZODB#178]
I am able to save only the visual representation of the DataFrame, not the data itself. Serializing via a ZEO instance.

**Comment by jamadden** [comment]
In general, ZODB only uses the standard `pickle` functionality to load and store objects. If an (extension) type doesn't support that, it can't be properly used with ZODB without providing custom support.

One such custom support for pandas objects is https://github.com/jimfulton/pheather
