### ISSUE TITLE
ZODB.serialize.ObjectWriter should fall back to __reduce__() right?

### ISSUE THREAD

**Issue by fried** [zopefoundation/ZODB#18]
I know I am trying some 'black magic', but I am creating dynamic classes. I would like to store these in ZODB. These run-time classes implement `__getnewargs__` and `__reduce__` as well as subclass Persistent.  Pickle will dump and load them, because of `__reduce__` providing a viable callable to reproduce these dynamic classes. 

ZODB fails with PicklingError because the type(obj) is not the same as the global
Now I have gotten it to work using a dirty workaround

``` python
from ZODB.serialize import ObjectWriter
orig_serialize = ObjectWriter.serialize
def _serialize(self, obj):
    try:
        return orig_serialize(self, obj)
    except:
        reduce = obj.__reduce__()  # contains (callable/class, newargs, __getstate__() )
        if reduce[1]:
            meta = reduce[0], reduce[1]
        else:
            meta = reduce[0]
        return self._dump(meta, reduce[2])
ObjectWriter.serialize = _serialize
```

Now my dirty workaround works, but I would much rather have the existing serialize method have this functionality

**Comment by jamadden** [comment]
Pickle protocol 1, currently in use in Python 2, doesn't call `__getnewargs__`, for that we'd need protocol 2+ (see #179 ):
```pycon
>>> class X(object):
...     def __getnewargs__(self):
...       raise Exception("getnewargs")
...
>>> import cPickle
>>> cPickle.dumps(X(), 1)
'ccopy_reg\n_reconstructor\nq\x01(c__main__\nX\nq\x02c__builtin__\nobject\nq\x03NtRq\x04.'
>>> cPickle.dumps(X(), 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in __getnewargs__
Exception: getnewargs
```

**Comment by jimfulton** [comment]
@fried 

Are these the same as persistent classes?

Perhaps take a look at src/ZODB/persistentclass.*

What version of Python are you using?

**Comment by jamadden** [comment]
There've been no comments from the OP since 2014, and the pickle protocol has been updated which theoretically solves this, so I'm going to go ahead and close it.
