### ISSUE TITLE
Cannot change "_p_changed" property

### ISSUE THREAD

**Issue by vlad1777d** [zopefoundation/ZODB#190]
Hello.

I don't know, is it right place for this.

There are two main files:
./packages/sanic_session/zodb_session_interface.py
./packages/sanic_session/tests/test_zodb_session_interface.py
here: [times_new_novel_asyncio.zip](https://github.com/zopefoundation/ZODB/files/1718402/times_new_novel_asyncio.zip)

Second contains test to first. After installing dependencies and activating venv, if to make `python -m pytest ./packages/sanic_session/tests/test_zodb_session_interface.py`
, than in last test if not to do transaction.commit(), you can't change "_p_changed" property to True of subclass of Persistent class (is located at first file).

But if to make `session_interface.zodb_transaction.commit()`, which is located on line 172, than`_p_changed` property of Persistent subclass will change.

In other test files, for example, all is going well.
For example, in ./test_zodb.py

Can somebody suggest, why is it happning ?

Thank you.

Best regards, Vladislav

**Comment by tseaver** [comment]
The `_p_changed` property is part of the `Persistent` class implementation, whose [repository](https://github.com/zopefoundation/persistent) would be a better place to report the issue.  

If you do report it there, you'd be more likely to get help if you can create a minimal testcase (ideally, a single Python fragment) which reproduces the problem:  a zipfile of your whole project environment is too much information.

**Comment by vlad1777d** [comment]
@tseaver , understood, thank you.
