### ISSUE TITLE
MANIFEST.in issues

### ISSUE THREAD

**Issue by agroszer** [zopefoundation/ZODB#23]
$ check-manifest 
listing source files under version control: 173 files and directories
copying source files to a temporary directory
building an sdist: ZODB-4.0.1dev.tar.gz: 165 files and directories
files in version control do not match the sdist!
missing from sdist:
  .travis.yml
  COPYING
  bootstrap.py
  buildout.cfg
  ez_setup.py
  log.ini
  release.py
  tox.ini
suggested MANIFEST.in rules:
  include *.py
  include .travis.yml
  include COPYING
  include buildout.cfg
  include log.ini
  include tox.ini

**Comment by tseaver** [comment]
Via a2dc2e321eb65f898f8b27d9e0bc2844c8835e09 and 43f0160eb13a26258828c207c514f2db24eabbaa
