### ISSUE TITLE
ReadOnly DemoStorage

### ISSUE THREAD

**Issue by azmeuk** [zopefoundation/ZODB#236]
Hi. I am using `DemoStorage` for my unit tests and `ZEO+FileStorage` in production, in a web application.

For the sake of performance I would like to replicate my production ZEO database with ZRS. This way I could plug readonly pages on the replicated database (more or less the GET pages of my application) and keep the others pages plugged on the read/write database (more or less the POST pages of my application).

To be sure my GET web pages do not commit anything, I would like to connect the GET pages unit tests to a read only database. This way I could expect to see a `ReadOnlyException` in my unit tests if there is a unauthorized commit. I would like to use something like this:

```python
rw = DemoStorage()
ro = DemoStorage(base=rw, read_only=True)
```

I would like to stick with `DemoStorage` instead `FileStorage` for unit testing, because it is faster and easier to setup and destroy.

Currently, `DemoStorage` cannot be used in a read only mode. Is it something planed, or that you may want to implement? If not, would you accept pull requests for such a feature?

**Comment by jimfulton** [comment]
I think this is a great idea, however I suggest a slightly different approach.

Rather than adding readonlyness to to DemoStorage, create ReadOnlyStorage as a wrapper storage (like beforestorage or zlibstorage) that makes the wrapped storage read-only.

**Comment by azmeuk** [comment]
I have created a [readonlystorage](https://gitlab.com/yaal/readonlystorage) package, and it seems to do the trick! Thank you for your advice.

**Comment by icemac** [comment]
> I have created a [readonlystorage](https://gitlab.com/yaal/readonlystorage) package, and it seems to do the trick! Thank you for your advice.

Cool, is there a chance to link to this package on http://www.zodb.org/?
