### ISSUE TITLE
Deprecation warning on Python 3.8

### ISSUE THREAD

**Issue by icemac** [zopefoundation/ZODB#262]
`ZODB-5.5.1-py3.8.egg/ZODB/utils.py:141: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats  ts = ts.laterThan(TimeStamp(old))`

**Comment by mgedmin** [comment]
This is caused by https://github.com/zopefoundation/persistent/issues/108, I believe.

**Comment by icemac** [comment]
zopefoundation/persistent#109 is now merged ad awaits a release, so we can depend on it here.

**Comment by jamadden** [comment]
persistent 4.5.0 has been released to PyPI. Do we want to make that part of a version constraint here?

**Comment by mgedmin** [comment]
My gut feeling is "no", but I might be convinced.

**Comment by icemac** [comment]
`persistent >= 4.5` is no hard constraint. Using older versions only triggers this deprecation warning.
