### ISSUE TITLE
ValueError: insecure string pickle 

### ISSUE THREAD

**Issue by zopyx** [zopefoundation/ZODB#276]
Plone 5.2RC3, ZODB 5.5.1

We moved Plone instance to Plone 5.2RC3 - fresh installation, all content created over plone.restapi.

Today I encountered the following error on the `__annotations__` attribute which holds Plone specific and application specific annotations. The error clearly is related to a "clear cache" operation in our code which deletes a particular annotation and refills it with updated data (a dict).

```
 Module chameleon.template, line 209, in render
  Module chameleon.utils, line 75, in raise_with_traceback
  Module chameleon.template, line 187, in render
  Module 4ca387f63775c64ebcc5b27106afa95e.py, line 1750, in render
  Module fac76ee8da75cb24ddd905995267f23c.py, line 444, in render_master
  Module plone.app.layout.globals.layout, line 97, in have_portlets
  Module plone.portlets.manager, line 49, in visible
  Module plone.portlets.manager, line 69, in portletsToShow
  Module plone.portlets.manager, line 72, in allPortlets
  Module plone.memoize.view, line 48, in memogetter
  Module plone.portlets.manager, line 109, in _lazyLoadPortlets
  Module plone.portlets.retriever, line 108, in getPortlets
  Module plone.portlets.assignable, line 58, in getBlacklistStatus
  Module plone.portlets.assignable, line 68, in _getBlacklist
  Module zope.annotation.attribute, line 68, in get
  Module ZODB.Connection, line 795, in setstate
  Module ZODB.serialize, line 633, in setGhostState
  Module ZODB.serialize, line 626, in getState
ValueError: insecure string pickle
```

The only option was to resurrect the related values for the annotations from a backup and clearing the old OBTree instance of the `__annotations__` object in advance.

**Comment by jamadden** [comment]
That's an error reported by the underlying [pickle library](https://github.com/zopefoundation/zodbpickle/blob/master/src/zodbpickle/_pickle_27.c#L3817). 

As far as I can tell, that error only occurs with the very oldest original pickle protocol 0 (as that's the only protocol that uses that opcode; protocol 1 and higher use `BINSTRING`), and it indicates a malformed (truncated) pickle:

```pycon
>>> import cPickle as pickle
>>> import pickletools
>>> pickle.dumps('foo')
"S'foo'\np1\n."
>>> pickletools.dis("S'foo'\np1\n.")
    0: S    STRING     'foo'
    7: p    PUT        1
   10: .    STOP
highest protocol among opcodes = 0
>>> pickle.loads("S'foo") # lose the terminating '
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: insecure string pickle
```

What's strange, though, is that as far back as ZODB 3.3, ZODB was storing pickles using protocol 1, which as mentioned doesn't use that opcode:
```pycon
>>> pickle.dumps('foo', 1)
'U\x03fooq\x01.'
>>> pickletools.dis('U\x03fooq\x01.')
    0: U    SHORT_BINSTRING 'foo'
    5: q    BINPUT     1
    7: .    STOP
highest protocol among opcodes = 1
```

**Comment by zopyx** [comment]
The Plone site was created from scratch with the given Plone and ZODB versions. Everyt.hing on top of Python 3.7

**Comment by mgedmin** [comment]
There was that recent zodbpickle bug on Python 3 that could corrupt pickle data under some circumstances: https://github.com/zopefoundation/zodbpickle/pull/47.  Can you check what zodbpickle version you had installed?  Any version before 1.0.4 had that problem.  (1.0.4 was released on June 12, and your bug report sounds like a more recent thing, so maybe this is a red herring.  Unless Plone pins versions and hasn't updated the zodbpickle version pin?)

BTW the latest zodbbrowser version lets you inspect raw pickle data (the output of pickletools.dis() actually), which might or might not help debug this.

**Comment by zopyx** [comment]
zodbpickle==1.0.3

This might explain the problem....will upgrade..
