### ISSUE TITLE
Savepoint commit logging is misleading (and potentially expensive)

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/ZODB#282]
When savepoints are in use, `ZODB.Connection` logs something like this (notice that's *80GB*):
```
DEBUG [ZODB.Connection]] Committing savepoints of size 86970105856
```

https://github.com/zopefoundation/ZODB/blob/2f8cc67a3ba389337595107c6f3e3d98ec68521a/src/ZODB/Connection.py#L1026-L1033

Where `src` is a `TmpStore`. `TmpStore` copies the `getSize()` method from the underlying original storage, so what's being logged isn't the size of the savepoint, it's the size of the *entire database*.

https://github.com/zopefoundation/ZODB/blob/2f8cc67a3ba389337595107c6f3e3d98ec68521a/src/ZODB/Connection.py#L1131-L1141 

On RelStorage, in order to provide a consistent, up-to-date answer (and be usable no matter what else the state of the storage is) this always opens a new connection to the database, which can be slow.

https://github.com/zodb/relstorage/blob/2c8997d6c862de7e6a4d9f2a8d368a5471e93ff7/src/relstorage/adapters/postgresql/stats.py#L45-L50

Perhaps what we want to log is `len(src)`? That's the number of entries in the `TmpStore`.

**Comment by jmuchemb** [comment]
Why not `src.position` ?

**Comment by jmuchemb** [comment]
BTW, IStorage defines both `__len__` & `getSize` so it's not consistent that TmpStore redirects only 1 of them to the underlying storage.

**Comment by jamadden** [comment]
`src.position` includes extra header data for each object and I think in the event of multiple savepoints that write the same OID more than once it also includes duplicates, but I haven't looked that closely. Either way seems like an improvement.
