### ISSUE TITLE
tryToResolveConflict masks BTreesConflictError details

### ISSUE THREAD

**Issue by agroszer** [zopefoundation/ZODB#29]
Most important would be the reason
Including details in ConflictError might be hard, but what about

```
    except (ConflictError, BadClassName), e:
        logger.error(str(e))
```

Might duplicate log entries, but oh well...

**Comment by mgedmin** [comment]
Context (I'm guessing): https://github.com/zopefoundation/ZODB/blob/55ffc29ce9420dcffab022791ddc40008387bd82/src/ZODB/ConflictResolution.py#L297-L298

**Comment by agroszer** [comment]
right!
