### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by j-craig** [zopefoundation/ZODB#308]
It's been a year and a half since the last version was released and in that time transaction has released a new version which breaks the tests in the latest release of ZODB. Any chance we can get a new version released sometime soon?

**Comment by jmuchemb** [comment]
For me, #307 is a blocker.

**Comment by jmuchemb** [comment]
If there's no objection about #307, I'd like to make a release just after it is merged.

Should I wait for #310?

/cc @jamadden @janjaapdriessen

**Comment by jamadden** [comment]
I'd love to see those two get merged and released. I've updated my reviews of them.

**Comment by penn5** [comment]
Looking for a database, this seems to fit my requirements perfectly. Are there any major changes from the docs in this new version?

**Comment by jamadden** [comment]
Unreleased changes are documented in [CHANGES.rst](https://github.com/zopefoundation/ZODB/blob/master/CHANGES.rst) in the root of the repository.

**Comment by penn5** [comment]
Thanks!

**Comment by jmuchemb** [comment]
5.6.0 released
