### ISSUE TITLE
Drop python 2.7 support

### ISSUE THREAD

**Issue by penn5** [zopefoundation/ZODB#312]
Python 2.7 has been EOL for 6 months, so perhaps it is time to drop support?

**Comment by jugmac00** [comment]
Not specific to this repository, but there was a general discussion a while back...

**Comment by mgedmin** [comment]
https://github.com/orgs/zopefoundation/teams/developers/discussions/2 is a more permanent URL for that discussion, or we could refer to https://github.com/zopefoundation/meta/issues/15.

TL;DR: consensus seems to be that there are still people who want to support Python 2 (e.g. PyPy is not EOL), and there are no good arguments for making their life harder.
