### ISSUE TITLE
Explicit PyPy Support (in progress)

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/ZODB#33]
ZODB currently does not cleanly pass a test run under PyPy --- there are numerous failures.

Part of this is due to the lack of `noload` in PyPy's "cPickle" module (which is actually implemented in Python) --- this is easily solved through the use of `zodbpickle` (which is already a dependency). At least part of the rest of it is due to differences in the C and pure-Python implementations of `persistent` (e.g., the Python `PickleCache` lacks some size attributes found in the C version). 

Hopefully the rest are minor differences, but I'm not sure yet. I'm working on a branch at https://github.com/NextThought/ZODB/tree/pypy to find out, and hopefully fix them (looks like some other PRs in `persistent` will be useful, too).

I'm opening this issue to let people know someone is working on this, and maybe to have a place to ask for help if I get stuck :)

**Comment by jamadden** [comment]
As of now, the `ZODB` code in [this ZODB branch](https://github.com/NextThought/ZODB/tree/pypy)   together with the `persistent` code in [this branch](https://github.com/NextThought/persistent/tree/zodb-on-pypy-support) runs all 930 unit tests. The modifications to ZODB are very minimal, most of the changes are in `persistent`.

The functional tests still have some issues. I'm guessing those are mostly refcounting/GC related. I'll look into those next.

**Comment by jamadden** [comment]
Update: All 482 functional tests now run under PyPy using those branches.

**Comment by jamadden** [comment]
With  the `ZODB` code in [this branch](https://github.com/NextThought/ZODB/tree/pypy)  and the `persistent` code in [this branch](https://github.com/NextThought/persistent/tree/zodb-on-pypy-support), the version of `ZEO` in [this branch](https://github.com/NextThought/ZEO/tree/pypy-support)  passes all of its unit and functional tests. I'll start opening PRs for ZODB and ZEO as soon as `persistent` gets merged.

**Comment by gotcha** [comment]
@jamadden branch of persistent has been merged and released as 4.0.9

**Comment by jamadden** [comment]
@gotcha We are waiting on zopefoundation/persistent#20 to be merged and released as 4.0.10.

**Comment by tseaver** [comment]
I've just doint a review of https://github.com/zopefoundation/persistent/pull/20

**Comment by jamadden** [comment]
@tseaver Thank you! I know there's a lot to review there. The PRs for ZODB and ZEO are (currently) much smaller.

**Comment by tseaver** [comment]
I don't see a PR for ZEO.

**Comment by tseaver** [comment]
Actually, I don't see one for ZODB, either:  are both pending landing https://github.com/zopefoundation/persistent/pull/20?

**Comment by jamadden** [comment]
Yes. I could open them now, but they would fail all the Travis tests until that PR gets merged and released.
