### ISSUE TITLE
http://zodb.org is down

### ISSUE THREAD

**Issue by icemac** [zopefoundation/ZODB#334]
The error message at http://zodb.org  says:

```
404 - Invalid Host

The host "zodb.org" is unknown to Read the Docs

If you control this domain and believe this is in error, please review our custom domain documentation. In the past, we allowed custom domains to point to us without configuring the domain in the Read the Docs dashboard and we attempted to intelligently guess the correct project based on DNS settings. Now, we believe that explicit is better than implicit. Below are some steps to help you get your domain working again:

* Ensure you have a CNAME record pointing to readthedocs.io
* Add your desired domain in the Read the Docs dashboard for your project (under Your Project >> Admin >> Domains)
```

I do no know where it used to point to.
For https://readthedocs.org/projects/zodb/ @cguardia seems to be the only project admin. But it points to a personal repository.

Is there anyone who can bring a bit of light into this issue, maybe @dataflake?

**Comment by dataflake** [comment]
The IP address that `zodb.org` was pointing to,  74.220.203.54, is no longer reachable. I don't know where that server is and have no control over it. I have control over the DNS zone for zodb.org and attempted to repair the problem by replacing the record for `zodb.org` with a CNAME record pointing to `zodb-docs.readthedocs.io`, which is what `www.zodb.org` has been using. Obviously that does not work, either, so I have restored the old record pointing to 74.220.203.54.

Like I said, there's nothing I can do about that server, and I don't know who could go into the RTD configuration for the ZODB docs to add `zodb.org` as allowed domain for redirecting to RTD.

**Comment by dataflake** [comment]
I have added a simple Apache config and LE certificate for the hostname `zodb.org` on the server we control and changed the DNS record. All it does is permanently redirect to `www.zodb.org`, which has the CNAME record pointing to RTD. Once DNS propagation has finished this should work.

**Comment by icemac** [comment]
According to https://readthedocs.org/projects/zodb-docs/ @jimfulton is the only one who can administer `zodb-docs` at RTD.

@jimfulton Could you please add me (`icemac`) as developer at https://readthedocs.org/projects/zodb-docs/?

**Comment by jimfulton** [comment]
Done. Sorry, I thought this had been fixed, as I can see the docs. <shrug>

Thanks everyone for all the help on this.  I've been MIA. :(

**Comment by icemac** [comment]
As https://zodb.org now again shows the documentation I am closing this issue in favor of #335.

Thank you everyone who contributed to the solution.
