### ISSUE TITLE
Connecting to ClientStorage using a Windows machine

### ISSUE THREAD

**Issue by davepruitt** [zopefoundation/ZODB#349]
I have ZEO running on a Windows machine. It seems to be running fine, as far as I can tell.

I have another Windows machine that wants to connect to the ZEO server and access the ZODB database that is being served by that server.

I am using the following lines of code:

```
from ZODB import DB
from ZEO import ClientStorage
storage = ClientStorage.ClientStorage(the_ip_address_of_the_server, the_port_of_the_server)
db = DB(storage)
connection = db.open()
root = connection.root()
```

Unfortunately, I get an error on the 3rd line of code:

```
storage = ClientStorage.ClientStorage(the_ip_address_of_the_server, the_port_of_the_server)
```

The error is: 

> ValueError: Unix sockets are not available on Windows

What is happening here? Does using ClientStorage only function properly on Unix machines? This doesn't seem right. Any advice?

**Comment by d-maurer** [comment]
David wrote at 2021-8-23 01:37 -0700:
>I have ZEO running on a Windows machine. It seems to be running fine, as far as I can tell.
>
>I have another Windows machine that wants to connect to the ZEO server and access the ZODB database that is being served by that server.
>
>I am using the following lines of code:
>
>```
>from ZODB import DB
>from ZEO import ClientStorage
>storage = ClientStorage.ClientStorage(the_ip_address_of_the_server, the_port_of_the_server)

You have not told us which `ZEO` version you are using.
On modern `ZEO` versions (5.2.x), `ClientStorage.__init__` has the signature:
                 self, addr, storage='1', cache_size=20 * MB,
                 name='', wait_timeout=None,
		 ...
Thus, you are supposed to pass IP address and port in a single
parameter (named `addr`).

While there may be signature differences with other versions, I assume
this is not the case for the `addr` specification.

**Comment by davepruitt** [comment]
Both the server and the client computers have ZEO 5.2.3 and ZODB 5.6.0 installed.

The ZEO configuration file looks like the following:

```
<zeo>
  address my_ip_address:8090
</zeo>

<filestorage>
  path C:/zeo_server/my_database_filename.fs
</filestorage>
```

When I run the ZEO server, the output is the following:
```
c:\zeo_server>runzeo -C zeo_server.config
------
2021-08-23T05:05:39 INFO ZEO.runzeo (10436) opening storage '1' using FileStorage
------
2021-08-23T05:05:40 INFO ZEO.StorageServer StorageServer created RW with storages: 1:RW:C:/zeo_server/my_database_filename.fs
------
2021-08-23T05:05:40 INFO ZEO.asyncio.server listening on ('ip.ip.ip.ip', 8090)
```

Both of the following lines of code produce the ValueError that I mentioned above:
```
storage = ClientStorage.ClientStorage('ip.ip.ip.ip:8090')
storage = ClientStorage.ClientStorage('ip.ip.ip.ip', 8090)
```

**Comment by davepruitt** [comment]
Changing it to be in tuple form worked. Thank you for your help!
