### ISSUE TITLE
Any objections to releasing 5.7.0?

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/ZODB#359]
Having 5.7.0 and its official support for Python 3.9 and 3.10 would make it easier to test packages like ZEO. Are there any reasons against a release? I don't mind doing it.

**Comment by icemac** [comment]
Yes, please cut a new release.
I would have done it myself but I have no PyPI rights for doing so.

**Comment by dataflake** [comment]
ZODB 5.7.0 is now released after some hiccups with tests. @icemac I don't have rights to add anyone to the project on PyPI, you could ask Jim or Tres.

**Comment by icemac** [comment]
Thank you for the release.
