### ISSUE TITLE
PyInstaller fails to find ZODB's config.xml and exe will no run when using a provided config from URL

### ISSUE THREAD

**Issue by CtheCondor** [zopefoundation/ZODB#366]
### What I did:
PyInstaller on testserver.py 
Pyinstaller --onefile  --clean testserver.py 
with hidden_import=['_cffi_backend'] # added to the Spec file after the first run attempt showed the error

```python
from ZEO import ClientStorage
import ZODB.config
db=ZODB.config.databaseFromURL(xPath)
conn=db.open()
print(conn.root['test'])
```
Using Poetry with 
zeo="^5.3"
pyinstaller = "^5.2"
ZODB="^5.7.0"
cffi="^1.15.1"

### What I expect to happen:
print the list in the root 'test' 'leaf'
### What actually happened:
"winError 3 the system cannot find the path specified 'C\Users\owner\AppData\Local\Temp\2\_MEI200522\ZODB\config.xml"
### What version of Python and Zope/Addons I am using:
ZSEe above

Windows 10

Note cannot attach output directly as it is being run on a closed network computer. 

I also tried using storage=ClientStorage.ClientStorage(addr)
then db=DB(storage)
 and the exe using that method works... but I need the address/port to be read from as script as it rotates between two LAN computers based on which is plugged in.

**Comment by d-maurer** [comment]
CtheCondor wrote at 2022-7-28 17:39 -0700:
> ...
>### What I did:
>PyInstaller on testserver.py
>Pyinstaller --onefile  --clean testserver.py
>with hidden_import=['_cffi_backend'] # added to the Spec file after the first run attempt showed the error
>
>```python
>from ZEO import ClientStorage
>import ZODB.config
>db=ZODB.config.databaseFromURL(xPath)
>conn=db.open()
>print(conn.root['test'])
>```
> ...
>### What actually happened:
>"winError 3 the system cannot find the path specified 'C\Users\owner\AppData\Local\Temp\2\_MEI200522\ZODB\config.xml"

I do not think that this is a `ZODB` problem -- maybe apart
from reading data files (like `config.xml`) which might not
be fully supported by `PyInstaller` (maybe with the `onefile` option).
I found an indication at
"https://pyinstaller.org/en/stable/operating-mode.html#bundling-to-one-file":
    A disadvantage is that any related files such as a README must be
    distributed separately.
This indicates that non Python files (e.g. configuration files)
might not be (automatically) included in the bundled file.

Please follow the `PyInstaller` advice (found at the end of the link
above):
    Before you attempt to bundle to one file, make sure your app works
    correctly when bundled to one folder. It is is much easier to
    diagnose problems in one-folder mode.

Also read carefully the `PyInstaller` documentation section
"https://pyinstaller.org/en/stable/operating-mode.html#analysis-finding-the-files-your-program-needs". It contains:
    If your program depends on access to certain data files, you can
    tell PyInstaller to include them in the bundle as well. You do
    this by modifying the spec file, an advanced topic that is covered
    under Using Spec Files.
This suggests that `PyInstaller` requires special configuration
to include data files (such as `ZODB`'s `config.xml`) into the bundle.

**Comment by CtheCondor** [comment]
Thank you for your assistance I have modified my approach with PyInstaller and it resolved my issue.
