### ISSUE TITLE
Switch test name prefix from `check` to `test`.

### ISSUE THREAD

**Issue by icemac** [zopefoundation/ZODB#377]
Newer Python versions deprecate using `unitest.makeSuite`. The replacement `unittest.defaultTestLoader.loadTestsFromTestCase` does not support to specify a prefix to find the test functions but expects to be `test`.

ZODB seems to use `check` a method name prefix for the tests functions. (At least is this what I have seen in external storage implementations reusing ZODBs test harness, like `zc.zlibstorage`.)

Suggestions: Accept that test methods nowadays are prefixed with `test` and adapt ZODB tests to that prefix.

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2023-3-1 23:31 -0800:
> ...
>ZODB seems to use `check` a method name prefix for the tests functions. (At least is this what I have seen in external storage implementations reusing ZODBs test harness, like `zc.zlibstorage`.)

`ZEO`, too, uses tests from `ZODB` and (some of) its tests may require
to adapt to changes of `ZODB` tests.

**Comment by dataflake** [comment]
I have always wondered why those tests used the non-standard "check" prefix. I can't see any reason to deviate from the norm here.
