### ISSUE TITLE
PyPI Owner rights for ZODB

### ISSUE THREAD

**Issue by icemac** [zopefoundation/ZODB#387]
Currently there are only four maintainers listed at https://pypi.org/project/ZODB/.
Dataflake is just a "maintainer" (not an "owner") so no-one of the current Zope release managers can add new people to this project on PyPI.

Thus I am requesting the owner role for `dataflake` or me (`icemac`).

CC-ing the current (possible) owners:

@jimfulton @tseaver @jmuchemb

**Comment by tseaver** [comment]
I've made @dataflake an owner, and invited @icemac as one too.

**Comment by icemac** [comment]
@tseaver Thank you!
