### ISSUE TITLE
Can different ZODB versions be used with zc.zrs replication? Is ZODB 5.5.1 safe for Zope 5.10?

### ISSUE THREAD

**Issue by georgpfolz** [zopefoundation/ZODB#399]
This question is zc.zrs related, but as the zc.zrs repository is closed, I hope it's ok to ask it here:

With latest version of ZRS (3.1.0), I can use ZODB 6.0 as master but I have to use ZODB 5.5.1 or earlier as slave (https://github.com/zopefoundation/zc.zrs/issues/6).
As far as I'm concerned, I'm fine with that, I only wonder if there are any caveats with:

- replicating across different ZODB versions (i.e. from 6.0 to 5.5.1)
- using ZODB 5.5.1 with the newest Zope version (5.10)

So I wonder which of these choices is the right one:

1. Replicating from ZODB 6.0 to ZODB 5.5.1
2. Using ZODB 5.5.1 on both master and slave

**Comment by d-maurer** [comment]
Georg Pfolz wrote at 2024-6-22 08:01 -0700:
>This question is zc.zrs related, but as the zc.zrs repository is closed, I hope it's ok to ask it here:
>
>With latest version of ZRS (3.1.0), I can use ZODB 6.0 as master but I have to use ZODB 5.5.1 or earlier as slave (https://github.com/zopefoundation/zc.zrs/issues/6).
>As far as I'm concerned, I'm fine with that, I only wonder if there are any caveats with:
>
>- replicating across different ZODB versions (i.e. from 6.0 to 5.5.1)
>- using ZODB 5.5.1 with the newest Zope version (5.10)
>
>So I wonder which of these choices is the right one:
>
>1. Replicating from ZODB 6.0 to ZODB 5.5.1
>2. Using ZODB 5.5.1 on both master and slave

When you look at `CHANGES.rst`, you see what changed in recent ZODB versions.

From my point of view, the changes do not seem to be important
to your use case.

**Comment by georgpfolz** [comment]
> When you look at `CHANGES.rst`, you see what changed in recent ZODB versions.

OK

> From my point of view, the changes do not seem to be important
to your use case.

Great! Thank you for clarifying
