### ISSUE TITLE
Is there a way to save all the undoInfo when packing?

### ISSUE THREAD

**Issue by idgserpro** [zopefoundation/ZODB#41]
I don't know if this is the correct place to add this issue, so feel free to close if inappropriate.

We're using Plone which uses Zope. In Zope2 we have an "Undo" tab that lists some information about the transactions:

![selecao_091](https://cloud.githubusercontent.com/assets/8203476/10666169/b7c307c4-78ae-11e5-9139-6c16eb4dea50.png)

We get this info by using [undoInfo](https://github.com/zopefoundation/Zope/blob/401b8edfb9d5f01ef90a3fdc9cf594cf6e2db0e4/src/App/Undo.py#L111):

```python
[{'description': '/Plone/folder_listing', 'size': 573, 'user_name': ' admin', 'id': 'A7KTm8ZgC0Q=', 'time': 1445450626.494181}, {'description': '/Plone/portal_quickinstaller/reinstallProducts', 'size': 1636907, 'user_name': ' admin', 'id': 'A7KTm55XNyI=', 'time': 1445450617.111098}, {'description': '/Plone/manage_delObjects', 'size': 70665, 'user_name': ' admin', 'id': 'A7KThLXFqpk=', 'time': 1445449242.602844}, {'description': '/Plone/atct_edit', 'size': 244, 'user_name': ' admin', 'id': 'A7KTc2rAXLs=', 'time': 1445448205.019863}, {'description': '/Plone/atct_edit', 'size': 3231, 'user_name': ' admin', 'id': 'A7KTc1N618w=', 'time': 1445448199.565591}, {'description': '/Plone/folder_listing', 'size': 573, 'user_name': ' admin', 'id': 'A7KTcz/Ptsw=', 'time': 1445448194.955793}, {'description': '/Plone/portal_quickinstaller/reinstallProducts', 'size': 1634373, 'user_name': ' admin', 'id': 'A7KTcxC6wBE=', 'time': 1445448183.920975}, {'description': '/Plone/manage_delObjects', 'size': 67971, 'user_name': ' admin', 'id': 'A7KTcsyp0kQ=', 'time': 1445448167.967976}, {'description': '/Plone/atct_edit', 'size': 244, 'user_name': ' admin', 'id': 'A7KTcY6ZhBE=', 'time': 1445448093.421798}, {'description': '/Plone/atct_edit', 'size': 2803, 'user_name': ' admin', 'id': 'A7KTcYC9YkQ=', 'time': 1445448090.173386}, {'description': '/Plone/folder_listing', 'size': 573, 'user_name': ' admin', 'id': 'A7KTcV9iAKo=', 'time': 1445448082.355349}, {'description': '/Plone/portal_quickinstaller/reinstallProducts', 'size': 1593303, 'user_name': ' admin', 'id': 'A7KTcTMyqRE=', 'time': 1445448071.999506}, {'description': '/Plone/manage_delObjects', 'size': 67932, 'user_name': ' admin', 'id': 'A7KTcPcptUQ=', 'time': 1445448057.92881}, {'description': '/Plone/portal_quickinstaller/reinstallProducts', 'size': 681680, 'user_name': ' admin', 'id': 'A7KTb6yxMxE=', 'time': 1445447980.474731}, {'description': '/Plone/manage_delObjects', 'size': 67945, 'user_name': ' admin', 'id': 'A7KTbNoEUZk=', 'time': 1445447811.097704}, {'description': '/Plone/portal_quickinstaller/reinstallProducts', 'size': 679331, 'user_name': ' admin', 'id': 'A7KTbKbS25k=', 'time': 1445447799.099296}, {'description': '/Plone/manage_delObjects', 'size': 67931, 'user_name': ' admin', 'id': 'A7KTbAUBiWY=', 'time': 1445447761.173282}, {'description': '/Plone/portal_quickinstaller/reinstallProducts', 'size': 676241, 'user_name': ' admin', 'id': 'A7KTazldHRE=', 'time': 1445447713.444623}, {'description': '/Plone/manage_delObjects', 'size': 67946, 'user_name': ' admin', 'id': 'A7KTZskwOu4=', 'time': 1445447447.153531}, {'description': '/Plone/portal_quickinstaller/reinstallProducts', 'size': 672906, 'user_name': ' admin', 'id': 'A7KTZpX2yWY=', 'time': 1445447435.147815}]
```
Then it's rendered in html.

When packing, we lose this information that would be useful in some situations. Is it feasible to write a log to disk (it can be the dict above that we got from undoInfo) of this information [when packing](https://github.com/zopefoundation/ZODB/blob/e76c5b0234fff2ce773b875e024a32ba1e07800b/src/ZODB/MappingStorage.py#L201)? This could be an environment variable if you don't want to add this overhead to all systems that use ZODB.

**Comment by gotcha** [comment]
I guess that you know that when you pack, you loose the possibility to undo to any of the states removed by packing.

I'd be interested to know why you want to keep the information.

**Comment by idgserpro** [comment]
This information is interesting to have to know the actions that users had with different urls, when deleting, publishing and such. In simple terms, an *auditing* perspective of modifications that were made to the database that's available out of the box when you just use the ZODB.

I don't know if this is out of the scope of ZODB - I'm interested in this feature from a Plone/Zope perspective. That's why I'm asking it here to know your opinion on this matter.

If it's not in the interest of ZODB developers and zopefoundation to have a feature like this, at least we now have a historic record of reasons that show why it shouldn't be done. 

Thanks in advance.

**Comment by jimfulton** [comment]
Undo information comes from the data that gets packed away, so no, there's no built-in way to keep undo information after packing.

**Comment by idgserpro** [comment]
@jimfulton what is your opinion about this feature? Disadvantages, complications and such? Why it shouldn't be done? Right now there's no built-in way to keep undo information after packing, but we think it would be a useful thing to have it like it's [explained in our last comment](https://github.com/zopefoundation/ZODB/issues/41#issuecomment-150634148).

**Comment by jimfulton** [comment]
I am ambivalent. I'm certainly not going to implement it.

**Comment by idgserpro** [comment]
@jimfulton I know this is not priority for your development, we're just afraid of trying to sponsor such development and have a rejected pull request if the developers don't think this feature belongs to ZODB. At least a historical record of "why this shouldn't be done" would be really nice.

Who do you think we can add to help in this discussion from https://github.com/zopefoundation/ZODB/graphs/contributors?

**Comment by jimfulton** [comment]
I don't have any problem with your use case at a high level.  It's not clear that it requires a change to ZODB.  If you want it badly enough to fund development, I suggest approaching it as an add on that can work without changing ZODB.  A good place to discuss the details would be the zodb list on google groups, https://groups.google.com/forum/#!forum/zodb

**Comment by tseaver** [comment]
Given how packing works, I'm doubtful that it would be reasonable to implement the "log packed-away records" feature *during* packing: there is no easily-accessible record of the transactions which are being packed away.

Instead, perhaps the feature could be based on a periodic script which logs all records between <last-timestamp> and <new-timestamp>;  one could then use the same <new-timestamp> to drive the pack.  Such a script could use the same ZODB API methods as the Zope "Undo" tab.

**Comment by idgserpro** [comment]
>  I'm doubtful that it would be reasonable to implement the "log packed-away records" feature during packing: there is no *easily-accessible* record of the transactions which are being *packed away*.

@tseaver This is a reasonable explanation of why it's not possible to have this feature as described in this issue. We're not so familiar with ZODB sourcecode to know these limitations (we're asking for this feature from a high level perspective) and that's why we started this discussion. If not asking too much, would you have a little more complete explanation of this limitation, if possible with some source code references?

> Instead, perhaps the feature could be based on a periodic script which logs all records between and ; one could then use the same to drive the pack. Such a script could use the same ZODB API methods as the Zope "Undo" tab.

We can indeed log all records: in fact, third party plugins in Plone world [do exactly that](https://pypi.python.org/pypi/collective.fingerpointing), but using the Zope event machinery instead of interacting directly with ZODB. The plugin "solves" the issue, but the idea here is to have this log file generated directly from ZODB, *out-of-the-box*, since it's already available using the undoInfo information. And this info would be useful not only to Zope/Plone users but to everyone that uses ZODB (no need to create a plugin that hooks to events in each framework). This seemed as a simpler and more reasonable solution than hooking to a a lot of events but now you're saying it's more complicated than it looks.

That's perfectly ok: having this technical information, at least we can point this issue to clients when we're confronted with "why we can't have this undo information on disk".

Thanks for stepping by.
