### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by clozinski** [zopefoundation/ZODB#73]
If you look in

https://github.com/zopefoundation/ZODB/tree/ZODB5/doc

There are three files.

zodb-guide.txt refers to a url, perhaps should be updated to be zodb.org

storage.pdf from 2004 still talks about versions.  Should that document still be there. 
How about renaming it to 2004-storage.pdf to give readers a hint as to its age.

And History was last updated in 2011.  maybe that should be merged with changes.rst int he root folder.

**Comment by jamadden** [comment]
Documentation is in the process of being updated and rewritten. The specific issues mentioned here have already been addressed. Perhaps this issue can be closed.
