### ISSUE TITLE
Provide a way to get blobstorage size

### ISSUE THREAD

**Issue by frisi** [zopefoundation/ZODB#8]
i'd like to extend [munin.zope](https://pypi.python.org/pypi/munin.zope/2.0) or [Products.ZNagios](https://pypi.python.org/pypi/Products.ZNagios/0.6#graphs-provided-by-munin-client-py) to return the size of blobstorages too.

is there a way to get these numbers via an api? 
running `du` on linux systems can take ages (and is not platform independent)

maybe it's better to keep track of added blobfiles and keep the size in bytes as a separate value redundantly

**Comment by idgserpro** [comment]
If you're planning to use `df`, you can get the blob location with this snippet:

```
db_name = 'main'
db = app.Control_Panel.Database[db_name]
base_dir = db._getDB()._storage.fshelper.base_dir
```

Then you can run the command you prefer to get info about the directory.
