### ISSUE TITLE
`python setup.py test` does not run the full test suite

### ISSUE THREAD

**Issue by jmuchemb** [zopefoundation/ZODB#94]
`lp440234_Setting__p_changed_of_a_Blob_w_no_uncomitted_changes_is_noop` (from `src/ZODB/tests/testblob.py`) is an example of test that is not run by:

```
$ python setup.py test
...
Ran 1145 tests in 179.874s

OK
```

I test by inserting an error in this test, and I get no failure. However:

```
$ python setup.py test -m ZODB.tests.testFileStorage
...
FAIL: lp440234_Setting__p_changed_of_a_Blob_w_no_uncomitted_changes_is_noop (ZODB.tests.testblob)
...
```

I also wonder if Travis runs all tests.

**Comment by jamadden** [comment]
"Fixed" in #219 by removing 'setup.py test' altogether.
